name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
autolabeler:
  - label: "breaking"
    title:
      - "/BREAKING CHANGE/i"
      - '/\w+!:/i'
  - label: "major"
    title:
      - "/BREAKING CHANGE/i"
      - '/\w+!:/i'
  - label: "minor"
    title:
      - "/feat/i"
  - label: "patch"
    title:
      - "/fix/i"
categories:
  - title: "Breaking Changes"
    labels:
      - "breaking-change"
  - title: "Notable Changes"
    labels:
      - "notable"
  - title: "Features"
    labels:
      - "feature"
  - title: "Performance Improvements"
    labels:
      - "performance"
  - title: "Bug Fixes"
    labels:
      - "fix"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Maintenance"
    labels:
      - "chore"
      - "ci"
      - "refactor"
      - "revert"
      - "test"
      - "style"
exclude-labels:
  - "skip-changelog"
category-template: "### $TITLE"
change-template: "- $TITLE @$AUTHOR ([#$NUMBER])"
change-title-escapes: '\<*_&#@'
template: |
  ## v$RESOLVED_VERSION

  $CHANGES
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
