name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Breaking Changes"
    labels:
      - "breaking-change"
  - title: "Notable Changes"
    labels:
      - "notable"
  - title: "Features"
    labels:
      - "feature"
  - title: "Performance Improvements"
    labels:
      - "performance"
  - title: "Bug Fixes"
    labels:
      - "fix"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Maintenance"
    labels:
      - "chore"
      - "ci"
      - "refactor"
      - "revert"
      - "test"
  - title: "All App Changes"
    labels:
      - "*"
    collapse-after: 1
exclude-labels:
  - "skip-changelog"
category-template: "### $TITLE"
change-template: "- $TITLE @$AUTHOR ([#$NUMBER]($URL))"
change-title-escapes: '\<*_&#@'
template: |
  ## v$RESOLVED_VERSION

  $CHANGES
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
