on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  add-conventional-commit-label:
    runs-on: ubuntu-latest
    steps:
    permissions:
      pull-requests: read
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}