name: Prepare new release

on:
  workflow_dispatch:
    inputs:
      versionBump:
        description: "Type of version bump (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - "false"
          - "minor"
          - "patch"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-root
  cancel-in-progress: true

jobs:
  prepare_release:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: get_tag
        run: |
          git branch --show-current
          git pull
          echo "::set-output name=version::v$(pnpm pkg get version | tr -d '\"')"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.version }}
          name: v${{ steps.get_tag.outputs.version }}
          # Automatically generate release notes based on commits
          generate_release_notes: true
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
